AWSTemplateFormatVersion: '2010-09-09'

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/gettingstarted.templatebasics.html
Resources:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpc.html
  wordsBotVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
        - Key: "context"
          Value: "words_bot"


  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html
  wordsBotPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref wordsBotVPC
      CidrBlock: 10.10.2.0/24
      MapPublicIpOnLaunch: "false"
      Tags:
        - Key: "context"
          Value: "words_bot"
        - Key: "subnet"
          Value: "private"

Outputs:
  BotVpcId:
    Value: !Ref wordsBotVPC
    Export:
      Name: "wordsBotVPC"
  BotPrivateSubnet:
    Value: !Ref wordsBotPrivateSubnet
    Export: 
      Name: "wordsBotPrivateSubnet"